name: test pymavlink

on: [push, pull_request]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change

jobs:
  build:
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        runner: ['ubuntu-20.04', 'ubuntu-22.04', 'macos-latest']
        python-version: ['host', '3.6', '3.10']
        deps: ['pip']
        install: ['pip', 'setup']
        include:
          - runner: ubuntu-20.04
            python-version: host
            deps: apt
            install: sudo-pip
          - runner: ubuntu-20.04
            python-version: host
            deps: apt
            install: sudo-setup
          - runner: ubuntu-22.04
            python-version: host
            deps: apt
            install: sudo-pip
          - runner: ubuntu-22.04
            python-version: host
            deps: apt
            install: sudo-setup
        exclude:
          - runner: ubuntu-22.04
            python-version: '3.6'
    
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        if: matrix.python-version != 'host'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with apt
        if: matrix.deps=='apt'
        run: |
          sudo apt update
          sudo apt install flake8 mypy python3-pytest python3-numpy
          sudo apt install python3-lxml python3-future
      - run: |
          env
          python -m site
      - name: Install dependencies with pip
        if: matrix.deps=='pip'
        run: |
          pip install flake8 pytest numpy mypy

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub web ui editor is 127 chars wide
          SELECT=C,E10,E11,E401,E502,E703,E8,E9,F,W191,W291,W292,W293,W391
          flake8 . --count --exit-zero --select=${SELECT} --max-complexity=10 --max-line-length=127 --statistics

      - name: Install mavlink message
        run: |
          git clone https://github.com/ArduPilot/mavlink.git
          ln -s $PWD/mavlink/message_definitions ../

      - name: Install pymavlink
        if: matrix.install=='setup'
        run: python setup.py build install
      - name: Install pymavlink
        if: matrix.install=='sudo-setup'
        run: sudo python setup.py build install
      - name: Install pymavlink
        if: matrix.install=='pip'
        run: pip install .
      - name: Install pymavlink
        if: matrix.install=='sudo-pip'
        run: sudo pip install .
      - name: gtest deps
        if: runner.os == 'Linux'
        run: sudo apt install -y libgtest-dev
      - name: gtest deps
        if: runner.os == 'macOS'
        run: brew install googletest
      - name: Lint generated python code
        run: |
          if [ "${{ matrix.python-version }}" = "3.5" ]
          then
            flake8 --ignore='W503,E203,E501,E741' --statistics dialects/v10/python2/*.py dialects/v20/python2/*.py
          else
            flake8 --ignore='W503,E203,E501,E741' --statistics dialects/
            mypy --config-file ./.github/workflows/mypy-generated.ini dialects/v10/*.py dialects/v20/*.py
          fi

      - name: Generate messages
        run: |
          ./test_generate_all.sh
      - name : Test generators
        run: |
          ./test_generator.sh

      - name : Test JavaScript Bindings - generated tests and Mocha tests
        run: |
          ./test_gen_js.sh && cd generator/javascript && npm test && cd -

      - name: Test with pytest
        run: |
          python -m pytest
